---

- hosts: all
  remote_user: root
  tasks:

    # -------------------------------------------------------------------------
    # Freshen up the host
    # -------------------------------------------------------------------------

    - name: Disable dpkg fsync
      raw: test -e /etc/dpkg/dpkg.cfg.d/unsafe-io || echo force-unsafe-io > /etc/dpkg/dpkg.cfg.d/unsafe-io

    - name: Upgrade debian
      apt:
        update_cache: true
        upgrade: true

    # -------------------------------------------------------------------------
    # Install shit that should be there and fix locales
    # -------------------------------------------------------------------------

    - name: Create aws directory
      file:
        path: "/root/.aws"
        state: directory
        mode: '0755'
        
    - name: copy credentials
      template:
        src: credentials.j2
        dest: /root/.aws/credentials
        mode: '0600'
        
    - name: Download goofys
  	  get_url:
    	  url: https://github.com/kahing/goofys/releases/latest/download/goofys
    	  dest: /usr/local/bin/goofys
    	  mode: '777'
              
    - name: Run goofys
      raw: goofys --endpoint={{minioUrl}} {{bucket}} {{directory}}
      args: 
         executable: /bin/bash
